import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import Section from "@/components/Section";
import GovernanceTile from "@/components/GovernanceTile";
import {
  ArrowRight,
  Database,
  GitBranch,
  KeyRound,
  ScrollText,
  Sparkles,
} from "lucide-react";

export default function Governance() {
  const tiles = useQuery({ queryKey: ["governance-tiles"], queryFn: api.governanceTiles });
  const audit = useQuery({ queryKey: ["audit"], queryFn: api.audit });

  return (
    <div className="space-y-5">
      <div className="rounded-3xl border border-white/5 bg-water-grad p-6">
        <div className="text-[11px] uppercase tracking-[0.18em] text-white/70">
          Governance and lineage — synthetic
        </div>
        <h2 className="mt-1 text-2xl font-semibold tracking-tight text-white">
          Governed data. Governed AI. Governed actions.
        </h2>
        <p className="mt-1 max-w-2xl text-sm text-white/85">
          The Seqwater AI Command Centre is built on Databricks Unity Catalog,
          serverless SQL, Foundation Model APIs, Volumes, and Workflows — so
          executives, engineers, planners, and operators can interrogate trusted
          data with a clear audit trail.
        </p>
      </div>

      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">
        {(tiles.data ?? []).map((t) => (
          <GovernanceTile key={t.title} tile={t} />
        ))}
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Section
          title="Synthetic data lineage (illustrative)"
          description="Source → governed table → AI answer"
        >
          <ol className="relative space-y-3 pl-6">
            <span className="absolute left-2 top-2 bottom-2 w-px bg-white/10" />
            <LineageStep
              icon={<Database className="h-3.5 w-3.5 text-water-300" />}
              title="Synthetic source"
              detail="Generated by `scripts/generate_synthetic_data.py` with deterministic seed."
            />
            <LineageStep
              icon={<GitBranch className="h-3.5 w-3.5 text-aqua-300" />}
              title="Unity Catalog tables"
              detail="`main.seqwater_demo.assets`, `dam_storage_daily`, `water_quality_samples`, `asset_risk_scores`, `flood_scenarios`, `capital_projects`."
            />
            <LineageStep
              icon={<ScrollText className="h-3.5 w-3.5 text-amberop-300" />}
              title="Volume documents"
              detail="`/Volumes/main/seqwater_demo/operational_docs` — synthetic Markdown corpus indexed for retrieval."
            />
            <LineageStep
              icon={<Sparkles className="h-3.5 w-3.5 text-brand-300" />}
              title="AquaIQ tool calls"
              detail="`get_overview`, `get_top_asset_risks`, `get_water_quality_alerts`, `run_flood_readiness_scenario`, `get_capital_priorities`."
            />
            <LineageStep
              icon={<KeyRound className="h-3.5 w-3.5 text-catchment-300" />}
              title="Foundation Model API"
              detail="Endpoint abstraction (Llama, Claude, DBRX). Local mode uses deterministic mock."
            />
            <LineageStep
              icon={<ArrowRight className="h-3.5 w-3.5 text-ink-200" />}
              title="Executive answer"
              detail="Six-section response with source citations, confidence, and human validation requirement."
            />
          </ol>
        </Section>

        <Section
          title="Synthetic AI interaction audit"
          description="Every AquaIQ interaction is logged for review."
        >
          <div className="scrollbar-clean max-h-[420px] overflow-y-auto">
            <table className="w-full text-left text-xs">
              <thead className="sticky top-0 bg-ink-900/80 backdrop-blur">
                <tr className="text-[10px] uppercase tracking-wider text-ink-300">
                  <th className="px-2 py-2">Trace</th>
                  <th className="px-2 py-2">Time</th>
                  <th className="px-2 py-2">Tools</th>
                  <th className="px-2 py-2">Confidence</th>
                  <th className="px-2 py-2">Review</th>
                </tr>
              </thead>
              <tbody>
                {(audit.data ?? []).slice(0, 30).map((row) => (
                  <tr key={row.trace_id} className="table-row">
                    <td className="px-2 py-1.5">
                      <div className="font-mono text-[11px] text-ink-100">{row.trace_id}</div>
                      <div className="text-[10px] text-ink-300">{row.user_id}</div>
                    </td>
                    <td className="px-2 py-1.5 text-ink-200">
                      {new Date(row.timestamp).toLocaleString()}
                    </td>
                    <td className="px-2 py-1.5 text-ink-200">{row.tools_used}</td>
                    <td className="px-2 py-1.5 text-ink-200">{row.confidence}</td>
                    <td className="px-2 py-1.5 text-amberop-100">
                      {String(row.human_validation_required) === "true" || row.human_validation_required === true
                        ? "Required"
                        : "Optional"}
                    </td>
                  </tr>
                ))}
                {(!audit.data || audit.data.length === 0) ? (
                  <tr>
                    <td colSpan={5} className="px-2 py-6 text-center text-ink-300">
                      No synthetic audit rows yet. Ask AquaIQ a question to populate.
                    </td>
                  </tr>
                ) : null}
              </tbody>
            </table>
          </div>
        </Section>
      </div>

      <Section
        title="No black-box AI"
        description="Every AI output traces back to synthetic sources, tools, and review steps."
      >
        <div className="grid gap-3 md:grid-cols-3 text-sm">
          <Pillar title="Visible reasoning">
            Every AquaIQ answer includes the synthetic tools called, the synthetic
            sources used, the confidence band, and the human validation requirement.
          </Pillar>
          <Pillar title="Human-in-the-loop">
            AquaIQ refuses operational authorisation requests. Briefings carry an
            explicit human reviewer field. Operators can mark traces as helpful or
            requiring review.
          </Pillar>
          <Pillar title="Cost and access governance">
            Serverless SQL Warehouse for analytics queries, Foundation Model API for
            generation, Unity Catalog grants for data access — every layer has a
            clear cost line and access trail.
          </Pillar>
        </div>
      </Section>
    </div>
  );
}

function LineageStep({
  icon,
  title,
  detail,
}: {
  icon: React.ReactNode;
  title: string;
  detail: string;
}) {
  return (
    <li className="relative">
      <span className="absolute -left-[18px] top-1 flex h-5 w-5 items-center justify-center rounded-full border border-white/10 bg-ink-900">
        {icon}
      </span>
      <div className="rounded-xl border border-white/5 bg-white/[0.03] p-3 text-xs text-ink-200">
        <div className="text-sm font-semibold text-ink-50">{title}</div>
        <p className="mt-0.5">{detail}</p>
      </div>
    </li>
  );
}

function Pillar({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/5 bg-white/[0.03] p-4">
      <div className="text-[10px] uppercase tracking-wider text-ink-300">Governance pillar</div>
      <div className="mt-1 text-base font-semibold text-ink-50">{title}</div>
      <p className="mt-2 leading-relaxed text-ink-200">{children}</p>
    </div>
  );
}
